package com.myspace.task_assignments;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Address implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String city;
	private java.lang.String address;
	private java.lang.Integer zipcode;

	public Address() {
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.Integer getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(java.lang.Integer zipcode) {
		this.zipcode = zipcode;
	}

	public Address(java.lang.String city, java.lang.String address,
			java.lang.Integer zipcode) {
		this.city = city;
		this.address = address;
		this.zipcode = zipcode;
	}

}