package com.myspace.task_assignments;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MultiAddress implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.task_assignments.Address> manyAddress;
	private com.myspace.task_assignments.MultiAddress recursiveField;

	private java.time.LocalDateTime localDateTime;

	public MultiAddress() {
	}

	public java.util.List<com.myspace.task_assignments.Address> getManyAddress() {
		return this.manyAddress;
	}

	public void setManyAddress(
			java.util.List<com.myspace.task_assignments.Address> manyAddress) {
		this.manyAddress = manyAddress;
	}

	public com.myspace.task_assignments.MultiAddress getRecursiveField() {
		return this.recursiveField;
	}

	public void setRecursiveField(
			com.myspace.task_assignments.MultiAddress recursiveField) {
		this.recursiveField = recursiveField;
	}

	public java.time.LocalDateTime getLocalDateTime() {
		return this.localDateTime;
	}

	public void setLocalDateTime(java.time.LocalDateTime localDateTime) {
		this.localDateTime = localDateTime;
	}

	public MultiAddress(
			java.util.List<com.myspace.task_assignments.Address> manyAddress,
			com.myspace.task_assignments.MultiAddress recursiveField,
			java.time.LocalDateTime localDateTime) {
		this.manyAddress = manyAddress;
		this.recursiveField = recursiveField;
		this.localDateTime = localDateTime;
	}

}